### ISSUE TITLE
Leap year calculation incorrect

### ISSUE THREAD

**Issue by SnowsongWolf** [NorthernWidget/DS3231#10]
The leap year calculation is currently set to y % 4 == 0. The correct logic to determine a leap year is y % 4 == 0 && (y % 100 > 0 || y % 400 == 0). Every 4 years is a leap year except centuries, unless the year is divisible by 400. I.E. 2000 was a leap year, 1900 and 2100 are not.

**Comment by mrbesen** [comment]
i guess you could even simplify the ```y % 4 == 0```
with ```!(y&3)``` that would check if the lowest 2 bytes are set if so the number is not divisible by 4 so you have to but a not in front.

**Comment by awickert** [comment]
Thank you @mrbesen!
