### ISSUE TITLE
1.0.3 release not available via Arduino Library Manager

### ISSUE THREAD

**Issue by per1234** [NorthernWidget/DS3231#16]
The `version` value in library.properties was not updated before creating the 1.0.3 release of the library:
https://github.com/NorthernWidget/DS3231/blob/v1.0.3/library.properties#L2
That caused 1.0.3 to not get picked up by the Arduino Library Manager indexer job.

This means that anyone installing the library via Library Manager is getting an outdated version of the library.

**Comment by awickert** [comment]
Noted! At this point, it will be very outdated. I'll update library.properties and re-release accordingly with the new GitHub release.
