### ISSUE TITLE
Incompatibility with Arduino IDE 1.8.10

### ISSUE THREAD

**Issue by DotaPie** [NorthernWidget/DS3231#19]
There are macros "PM" and "RTC" present. Do not use these as variable names in examples (RTC) and in library (PM). Simply use low-case.

**Comment by awickert** [comment]
Good catch! Will clean up when able. Feel free to fork and PR.

**Comment by awickert** [comment]
Thanks to @ostaquet for cleaning this up. In my defense, these variable definitions predated Arduino's restriction of the namespaces :).
