### ISSUE TITLE
echo_time example file compile errors

### ISSUE THREAD

**Issue by OliB150** [NorthernWidget/DS3231#22]
First time using github, so apologies if this isn't in the format you'd expect; happy to take advice on improvements as necessary!

I've been trying to use the DS3231 Arduino library and decided to make a start with the "echo_time" example file as I believe my module still has a time inside it from when I used it some time ago. Upon doing so, I discovered that the example file cannot compile due to several errors, as follows:
- Line 33: 'Century' is not declared in scope
- Line 37: 'h12' is not declared in scope
- Line 37: 'PM' is not declared in scope
- Line 41/42: Missing '}' at the end of the for loop. Actual compile error points to line 44, but this is the cause.

For my general understanding of how these functions work, should the three variables simply need to be declared (as globals?) and 'passed' (as a pointer?) to the respective functions which will then change their value? Apologies if that's not the correct terminology!

Hope this helps.
Oli

**Comment by awickert** [comment]
Looks like this may have been a SAMD architecture issue that is now fixed (per https://github.com/NorthernWidget/DS3231/pull/23). Thanks to @ostaquet!
