### ISSUE TITLE
uninitialized const 'buff' [-fpermissive]

### ISSUE THREAD

**Issue by lbrutti** [NorthernWidget/DS3231#25]
Hello,
tried to compile a sketch for MKRFOX1200 and got this error:
`/Users/xxx/Documents/Arduino/libraries/DS3231-master/DS3231.cpp: In constructor 'DateTime::DateTime(const char*, const char*)'`
`/Users/xxx/Documents/Arduino/libraries/DS3231-master/DS3231.cpp:130:22: error: uninitialized const 'buff' [-fpermissive]
    static const char buff[4];`

I added the initialization code and everything was fixed, please consider my PR ;)

**Comment by hasenradball** [comment]
Hi replace the following line 130 with:
` static const char buff[4] {};`
The It should fixed!

**Comment by hasenradball** [comment]
Where is you PR?

**Comment by hasenradball** [comment]
see PR #28

**Comment by lbrutti** [comment]
youre right, just submitted it 👍

Il giorno dom 2 ago 2020 alle ore 10:04 Hasenradball <
notifications@github.com> ha scritto:

**Comment by hasenradball** [comment]
I also submitted one on the morning, lets see which one wins 😀

**Comment by awickert** [comment]
A whole train of snails passed you folks, but we're finally there!

**Comment by hasenradball** [comment]
hi 

what is the mesning of your comment?


Frank

**Comment by lbrutti** [comment]
Thanks for merging!

🙂

Have a nice day

--
Inviato da Android

Il Ven 12 Feb 2021, 06:49 Hasenradball <notifications@github.com> ha
scritto:

**Comment by awickert** [comment]
> hi 
> 
> what is the mesning of your comment?
> 
> 
> Frank
> 
> 
> > Am 12.02.2021 um 06:25 schrieb Andy Wickert <notifications@github.com>:
> > 
> > ﻿
> > A whole train of snails passed you folks, but we're finally there!
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Dass habe ich endlich der PR finalisiert :)
