### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by mike-s123** [NorthernWidget/DS3231#35]
@NorthernWidget

PRs for significant issues going back to last July, no response. I emailed the claimed maintainer, awickert@umn.edu, no response.

Is there anybody out there?

**Comment by awickert** [comment]
Just a terribly busy professor during the pandemic. Thanks for the email; finally got to it.

**Comment by awickert** [comment]
As a quick exoneration to myself -- it had been only a day or so between that email and this post! I'm not that bad :D
