### ISSUE TITLE
Teensy 4.0 Warning and unresponsive

### ISSUE THREAD

**Issue by Asvoria** [NorthernWidget/DS3231#43]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp: In constructor 'DateTime::DateTime(const char*, const char*)':
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:132:41: warning: writing into constant object (argument 3) [-Wformat=]
    sscanf(date, "%s %d %d", buff, &d, &y);
                                         ^
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:132:41: warning: format '%d' expects argument of type 'int*', but argument 4 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:132:41: warning: writing into constant object (argument 3) [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:132:41: warning: format '%d' expects argument of type 'int*', but argument 4 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 3 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
    sscanf(time, "%d:%d:%d", &hh, &mm, &ss);
                                          ^
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 4 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 5 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 3 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 4 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:135:42: warning: format '%d' expects argument of type 'int*', but argument 5 has type 'uint8_t* {aka unsigned char*}' [-Wformat=]
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp: In member function 'byte DS3231::getMonth(bool&)':
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:244:7: warning: unused variable 'hour' [-Wunused-variable]
  byte hour;
       ^
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp: At global scope:
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:138:16: warning: 'uint8_t conv2d(const char*)' defined but not used [-Wunused-function]
 static uint8_t conv2d(const char* p) {
                ^
C:\Users\admin\Documents\Arduino\libraries\DS3231\DS3231.cpp:158:16: warning: 'uint8_t bin2bcd(uint8_t)' defined but not used [-Wunused-function]
 static uint8_t bin2bcd (uint8_t val) { return val + 6 * (val / 10); }
#44

**Comment by awickert** [comment]
Thanks for PR https://github.com/NorthernWidget/DS3231/pull/44! Merged.
