### ISSUE TITLE
New versions are not published to Arduino library manager

### ISSUE THREAD

**Issue by wiiitek** [NorthernWidget/DS3231#74]
I can not see the version **1.1.1** in Arduino library description:

- https://www.arduino.cc/reference/en/libraries/ds3231/

And also (probably because of that) I can not install it with [arduino-cli](https://arduino.github.io/arduino-cli/) - it installs version 1.1.0:

```bash
$ arduino-cli lib install DS3231
Downloading DS3231@1.1.0...
DS3231@1.1.0 already downloaded
Installing DS3231@1.1.0...
Installed DS3231@1.1.0
```

While comparing version [1.1.0 and 1.1.1](https://github.com/NorthernWidget/DS3231/compare/v1.1.0...v1.1.1) I see that [library.properties](https://github.com/NorthernWidget/DS3231/blob/master/library.properties) were not updated, but not sure what else is needed to make new version of this library. See also: https://github.com/NorthernWidget/DS3231/issues/64#issuecomment-1237721412.

I know that I can install the library by [ZIP or GIT reference](https://arduino.github.io/arduino-cli/0.27/commands/arduino-cli_lib_install/#options) but it would be good if the newest version could be installed by Arduino IDE Library Manager:

![DS3231](https://user-images.githubusercontent.com/5294646/193131355-3ebebdd8-8977-40c7-ba0c-f3487e699bd0.jpg)

**Comment by designer2k2** [comment]
the `version`  tag in the library.properties file must be updated to 1.1.1 then it will work.

Currently it states: 
`version=1.1.0`
https://github.com/NorthernWidget/DS3231/blob/master/library.properties#L2
