### ISSUE TITLE
Wrong text in  DS3231/Documentation/Time-Retrieval.md 

### ISSUE THREAD

**Issue by GerardWassink** [NorthernWidget/DS3231#78]
In that document, under the description of the getYear() function, there's a piece of text as follows:
_/*
 * returns: byte = 00 to 99
 * parameters: none
 * asserts: none
 * side effects: none
 * DS3231 register addressed: 0x06
 */

**byte theDate = myRTC.getDate();**_

Which no doubt should have been:

_/*
 * returns: byte = 00 to 99
 * parameters: none
 * asserts: none
 * side effects: none
 * DS3231 register addressed: 0x06
 */

**byte theYear = myRTC.getYear();**_

Gerard

**Comment by IowaDave** [comment]
Good catch, thanks!  Closing this issue as resolved.
